from typing import Protocol


class PlatformBackend(Protocol):
    def enable_user(self, username: str) -> None: ...
    def disable_user(self, username: str) -> None: ...
    def force_logoff(self, username: str) -> None: ...
