"""initial

Revision ID: c073482aac09
Revises: 
Create Date: 2026-05-19 16:22:45.934391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c073482aac09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_name'), ['name'], unique=False)

    op.create_table('chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_child_id'), ['child_id'], unique=False)

    op.create_table('timewindow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timewindow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timewindow_child_id'), ['child_id'], unique=False)

    op.create_table('dailychorecompletion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chore_id'], ['chore.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chore_id', 'date')
    )
    with op.batch_alter_table('dailychorecompletion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dailychorecompletion_chore_id'), ['chore_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dailychorecompletion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dailychorecompletion_chore_id'))

    op.drop_table('dailychorecompletion')
    with op.batch_alter_table('timewindow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timewindow_child_id'))

    op.drop_table('timewindow')
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chore_child_id'))

    op.drop_table('chore')
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_name'))

    op.drop_table('child')
    # ### end Alembic commands ###
